version: "3"
services:
  app_react:
    build: ./gerenciador_dieta_frontend
    container_name: app_react
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_node

  banco:
    image: postgres
    container_name: banco
    ports:
      - 2345:5432
    env_file:
      - ./gerenciador_dieta_backend/.env.development
    volumes:
      - volume_banco:/var/lib/postgresql/data

  app_node:
    build: ./gerenciador_dieta_backend
    container_name: app_node
    ports:
      - 4000:4000
    env_file:
      - ./gerenciador_dieta_backend/.env.development
    volumes:
      - ./gerenciador_dieta_backend:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://banco:5432 -timeout 20s docker-entrypoint.sh
    command: bash -c "npm run dev:migration:run && npm run dev:migration:generate && npm run dev"
    depends_on:
      - banco

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react

volumes:
  build_react:
  volume_banco:
